### ISSUE TITLE
гранаты с пояса

### ISSUE THREAD

**Issue by alex-narrator** [xer-urg/xray-1.0007rc1#1]
#bug
при включенном дефайне GRENADES_FROM_BELT
1. гранаты тянутся в пояс из инвентаря
(вешаем на пояс РГД 5, достаём гранату, спокойно переключаемся сменой типа гранат на Ф1 даже если она не на поясе а в инвентаре). 
2. подсчет общего кол-ва гранат ведётся по всему инвентарю а не по доступным на поясе
3. при полностью заполненном поясе граната по даблклику улетает толи в слот толи в хрен пойми откуда взявшуюся невидимую ячейку на поясе. наверное всетаки в слот. такая же проблема если на поясе уже есть гранаты и мы хотим повесить на пояс например патроны - тоже улетят хрен пойми куда. с руганью в логе на no free room to place item. но не вылетает. вылетает если slot_persistent_4 = false. 
судя по всему граната активно хочет занять свой слот.
4. при отправке гранаты на пояс по даблклику ругань в логе на Bad slot 3

**Comment by alex-narrator** [comment]
2. косо-криво но починено - https://github.com/xer-urg/xray-1.0007rc1/commit/b7689a82dd6512b89e97f172bc4b916b2ae76c92
3. таки генерируется слот-ячейка на поясе. судя по всему или так или выводить на худ полноценный слот гранаты
4. судя по всему это отладочный варнинг, на работоспособность не влияет

**Comment by alex-narrator** [comment]
1. починено с помощью кода отсюда:
https://www.gameru.net/forum/index.php?s=&showtopic=67297&view=findpost&p=1617572
весь коммит - https://github.com/xer-urg/xray-1.0007rc1/commit/677eb191a79f104dc79d52c9ebd7e4372d558894

кол-во ячеек пояса должно быть на один меньше чем видимое кол-во на сетке пояса - чтобы было куда сгенерить слот-ячейку на поясе.

3. пока оставляем как есть. может таки добавим гранатный слот...

**Comment by alex-narrator** [comment]
Все работает - https://github.com/xer-urg/xray-1.0007rc1/commit/f2543538a575e57a62ea9bfa5307f5689b79b1d8

Пришлось добавить гранатный слот в инвентарь, но получилось симпатично. 
Кол-во ячеек на поясе может быть атким, каким нужно, без всяких условностей.

Есть мелкие шероховатости - "Небольшой баг - если при пустом слоте и наявных на поясе гранатах активировать слот бинокля, то гранату по клавише 4 достать не удастся. Придется спрятать бинокль и только потом достать гранату."

Закрывать пока не буду - пусть давит и напоминает.
Но, кажется, это таки победа)

**Comment by ForserX** [comment]
Кст, можно коммиты аттачить в топик при добавите коммитмесседж его хеш. К примеру: #2

**Comment by alex-narrator** [comment]
О, спасибо, буду знать тонкости)
Так конечно удобнее

**Comment by alex-narrator** [comment]
Сим коммитом закрываю https://github.com/xer-urg/xray-1.0007rc1/commit/8c42db8e5108dd4f5ede37ae80e9bfd14975e38a 
(а вот и нет)

Соврал.
Сим закрываю https://github.com/xer-urg/xray-1.0007rc1/commit/ef654ffdef47d78e8712da76c15e1e0a29a38e6b
